imagenet_node:
    prototxt_path: "/home/rikibot/Work/jetson-inference/data/networks/googlenet.prototxt"
    model_path: "/home/rikibot/Work/jetson-inference/data/networks/bvlc_googlenet.caffemodel"
    class_labels_path: "/home/rikibot/Work/jetson-inference/data/networks/ilsvrc12_synset_words.txt"

